Feature/ar 633 dependency injection 08 2021
os2display/display-client pull request #33
Opened 2021-08-12 10:37 UTC by sinejespersen

2021-08-19 07:29 UTC, turegjorup approved these changes

2021-09-07 09:54 UTC, tuj requested changes
I don't agree with the changes in this PR, please revert letting the slides decide when to call slideDone, and whether or not to use BaseSlideExecution or implementing something else.

2021-09-07 09:54 UTC, tuj commented on src/slide.js
> +  const slideExecution = new BaseSlideExecution(
This should not be initialized here and slideDone should not be removed from ImageText, etc
This is to support different ways of signaling that the slide is done.

2021-09-07 09:54 UTC, tuj commented on src/templates/baseSlideExecution.js
> +   * The duration of the slide.
This should be indented linke the other comments.

2021-09-10 09:59 UTC, closed without merging